<?php
echo $this->partialContent('header','admin', array('headbar'=>$this->headbar));
?>

<?php

if (QID) :
?>
<a href="<?php echo $this->url('show',false,'admin') ?>">Retour a la liste</a>
<?php if (QID>1) : ?>
<a href="<?php echo $this->url('show',array('qid'=> QID-1),'admin'); ?>">Question précédente</a>
<?php endif; ?>
<a href="<?php echo $this->url('show',array('qid'=> QID+1),'admin') ?>">Question suivante</a>
<?php
endif;
?>


<?php
foreach ($this->data as $qid => $qdata):
?>
<div class="box">
    <h1><a id="qid_<?php echo $qid ?>" href="<?php echo $this->url('show',array('qid'=>$qid),'admin') ?>"><?php echo $this->questions[$qid] ?></a>&nbsp;<a href="<?php echo $this->url('edit',array('qid'=>$qid),'admin') ?>"><img src="<?php echo $this->url('pencil_go.png',false,'public/images/') ?>" alt="edit"/></a></h1>
<?php
    foreach ($qdata as $rid => $rdata) :
?>
    <div id="response-<?php echo $qid ?>" class="line c-<?php echo ($rid % 2) ? 'a' : 'b' ?>">
        <span class="identifiant">#<?php echo $rid ?></span>
        <span class="response"><?php echo self::escape($rdata['reponse']) ?></span>
        <a class="detail">5 résultats associés</a>
    </div>
<?php
    endforeach;
?>
</div>
<?php
endforeach;
?>



<!--table class="response">
<?php
foreach ($this->data as $qid => $qdata):
?>
  <tr>
    <td colspan="3" class="question">
      <a id="qid_<?php echo $qid ?>" href="<?php echo $this->url('show',array('qid'=>$qid),'admin') ?>"><?php echo $this->questions[$qid] ?></a>&nbsp;<a href="<?php echo $this->url('edit',array('qid'=>$qid),'admin') ?>"><img src="<?php echo $this->url('pencil_go.png',false,'public/images/') ?>" alt="edit"/>
    </td>
  </tr>
<?php
    foreach ($qdata as $rid => $rdata) :
?>
  <tr>
    <td><span class="id"><?php echo $rid ?></td>
    <td width="300" class="response"><?php echo self::escape($rdata['reponse']) ?></td>
    <td>
<?php
        if (isset($this->response_points[$rid])) :
?>
      <table class="result">
        <thead>
          <tr>
            <th>rid</th>
            <th>name</th>
            <th>points</th>
          </tr>
        </thead>
        <tbody>
<?php
        foreach ($this->response_points[$rid] as $value) :
            if( !isset($points_summary[$value['result_id']]) ) {
                $points_summary[$value['result_id']] = 0;
            }
            $points_summary[$value['result_id']] += $value['points'];
?>
          <tr>
            <td><span class="id"><?php echo $value['result_id'] ?></span></td>
            <td><span><?php echo self::escape($value['result_name']) ?></span></td>
            <td><span class="points"><?php echo $value['points'] ?></span></td>
          </tr>
<?php
        endforeach;
?>
        </tbody>
      </table>
<?php
        else :
            echo "No results avaiable for this response.";
        endif;
?>
    </td>
  </tr>
<?php
    endforeach;
    if (isset($points_summary)) {
?>
  <tr>
    <td><span class="id">#</span></td>
    <td>Summaries</td>
    <td>
        <table class="result">
            <thead>
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>points</th>
                </tr>
            </thead>
            <tbody>
<?php
            foreach ($this->results_name as $_rid => $_rname) :
?>
                <tr>
                    <td>#</td>
                    <td><span><?php echo $_rname ?></span></td>
                    <td><?php echo $points_summary[$_rid]?></td>
                </tr>
<?php
            endforeach;
            unset($points_summary);
        ?>
            </tbody>
        </table>
    </td>
  </tr>
<?php
    }
endforeach;
?>
</table-->

<?php
echo $this->partialContent('footer','admin',false);
?>