<?php
echo $this->partialContent('header','all',false);
?>
<div id="container">
<form action="" method="post">
<p id="question">
<?php
echo $this->questions;
?>
</p>
<?php
echo $this->partialContent('qlist','index',null)->loop($this->data);
?>
<input name="submit" type="submit" value="Question suivante" />
</form>

<div id="progressbar">
    <div id="done" style="width:<?php echo $this->progressCssWidth ?>px"></div>
</div>

</div>
<?php
echo $this->partialContent('footer','all',false);
?>