
<div id="container">
<form action="" method="post">

<?php
echo $this->questions."<br/>\n";
$i=0;
foreach ($this->data as $qdata) {
		echo '<input type="radio" name="question_' . $qdata['qid'] . '" id="question_' . $i . '" value="' . $qdata['rid'] . '"> <label for="question_' . $i . '">' . self::escape($qdata['reponse']) . "</label><br/>\n";
		$i++;
}
?>

<input name="submit" type="submit" value="Question suivante" />

</form>
</div>