<?php echo "<?"; ?>xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Zombie Quizz : peux-tu survivre parmis les zombies ?</title>
	<link rel="stylesheet" href="<?php echo Taplod_ObjectCache::get('URL')->getBaseUri() ?>public/login.css" type="text/css" />
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$("label.inlined + .input-text").each(function (type){
				$(this).focus(function() {
					$(this).prev("label.inlined").addClass("focus");
				});
				$(this).keypress(function() {
					$(this).prev("label.inlined").addClass("has-text").removeClass("focus");
				});
				$(this).blur(function() {
					if ($(this).val() == "") {
						$(this).prev("label.inlined").removeClass("has-text").removeClass("focus");
					}
				});
			});
		});
	</script>
</head>
<body>
    <div id="container">
        <h1>Ayaq : quiz maker : login</h1>

        <?php echo showSessionMessages(); ?>

        <div id="loginbox">
            <form action="<?php echo $this->url('login') ?>" method="post">
                <label for="login" class="inlined">Your e-mail address</label> <input id="login" type="text" name="login" class="input-text" />
                <label for="password" class="inlined">Your password</label><input id="password" type="password" name="password" class="input-text" />
                <input type="submit" value="Get in !" />
            </form>
            <div class="notice"><a href="<?php echo $this->url('register') ?>">Don't have yet an account ?</a></div>
        </div>

        <div id="footer">
        powered by <a href="http://xrogaan.github.com/Ayaq/">Ayaq</a> &copy; Bellière Ludovic 2009
        </div>
    </div>
</body>
</html>
