<?php echo "<?"; ?>xml version="1.0" encoding="utf-8" ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Zombie Quizz : peux-tu survivre parmis les zombies ?</title>
	<link rel="stylesheet" href="<?php echo Taplod_ObjectCache::get('URL')->getBaseUri() ?>public/main.css" type="text/css" />
</head>
<body>
<?php echo showSessionMessages(); ?>